### ISSUE TITLE
invalid git repository

### ISSUE THREAD

**Issue by guitarvydas** [jmnavarrol/python-multigit#5]
I'm getting an exception on what I think is a valid repo.  To reproduce:
> git clone https://github.com/guitarvydas/eh.git
> cd eh
> multigit -r

successfully pulls git@github.com:guitarvydas/fmt-js.git 
but fails pulling git@github.com:guitarvydas/das.git

I built everything in a working directory and now am trying to test whether it works in a fresh directory.

This problem did not occur in the original working directory, but does occur when I cd to a fresh directory and try the above.  I haven't investigated yet to see if this is my own problem, thought I'd ask first...

I'm on MacOS (Monterey)
$ which multigit
/Users/tarvydas/.pyenv/shims/multigit

**Comment by jmnavarrol** [comment]
Hello and thanks for using python-mutigit!

I can reproduce your error.  I hope I have the time to work on this in the incoming two~three weeks.

At first glance, and possibly a workaround for you, I see that you already have a [populated 'das' directory](https://github.com/guitarvydas/eh/tree/master/das) in your main https://github.com/guitarvydas/eh repository that most possibly is getting in the way.

Can it be the case that either you splitted das into its own repository after a while and you forgot deleting its contents before using multigit, or that you forgot adding das directory to .gitignore in time and you checked it in your parent repo by mistake?

Hope this helps.

**Comment by guitarvydas** [comment]
Yes.  I started this repo before I discovered multigit and I populated das/ fully at that time.

rm'ing das/, pushing and running 'multigit -r' did work as a workaround

I don't expect to do this again, but I did do this when transitioning from the "old way" to the "new way" (not using multigit to using multigit).  Maybe the fix is simply an error message saying that "das/ already exists, please rm -f it first".

**Comment by jmnavarrol** [comment]
> I don't expect to do this again, but I did do this when transitioning from the "old way" to the "new way" (not using multigit to using multigit). Maybe the fix is simply an error message saying that "das/ already exists, please rm -f it first".

What happened to you is *"standard git behaviour"*: you can't clone a repo into an already busy directory, and I don't want multigit to be *"too clever"* but just allow for git sandboxes to be subdirectories in the most obvious way.

So, yes, I intend to fix this with an error/warning message instead of a crash, nothing fancy.

Thanks again for your feedback.

**Comment by jmnavarrol** [comment]
> So, yes, I intend to fix this with an error/warning message instead of a crash, nothing fancy.

[multigit v0.10.4](https://pypi.org/project/multigit/0.10.4) should fix the problem.  Now it throws an error message when it finds a directory it can't clone to.
