### ISSUE TITLE
Breaks on python 3.11

### ISSUE THREAD

**Issue by ecasilla** [jmnavarrol/python-multigit#8]
```dockerfile
FROM python:3.11


RUN pip3 install multigit


CMD ["tail", "-f", "/dev/null"]
```

May need to upgrade PyYAML-5.4.1 -> PyYAML-6.x

**Comment by jmnavarrol** [comment]
Hello @ecasilla:

It will take me some two or three weeks to spare the time to test this.  Currently I'm locked on PyYAML 5.4.1 for other reasons, so I'll have to have a look at how can I provided different dependencies for different Python versions (on top of that, I'm currently limited to Python 3.9, so that's something I will also have to deal with).

Thanks for letting me aware of this.

**Comment by jmnavarrol** [comment]
I could reproduce this bug.  Installation works at least up to Python 3.9.5 but breaks on at least starting Python 3.11.2.

Error comes in fact from PyYAML==5.4.1:
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      /tmp/pip-build-env-71q5ev9e/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!

The offending parameter is set on that version: https://github.com/yaml/pyyaml/blob/ee37f4653c08fc07aecff69cfd92848e6b1a540e/setup.cfg#L25

@ecasilla: for a workaround in the meantime you can build python-multigit from sources updating PyYAML version on setup.cfg to 6.0.1 and use that instead.

**Comment by jmnavarrol** [comment]
@ecasilla: you should be able to install **[multigit 0.11.4.post1](https://pypi.org/project/multigit/0.11.4.post1/)**.  It will use PyYAML 6.0.1 on Python >= 3.11 or PyYAML 5.4.1 otherwise.

**Comment by jmnavarrol** [comment]
I've been testing this new version both on Python 3.8~9 and 3.11 the last two weeks without problems, so I'll consider this as solved.
